# Generated by Django 4.2 on 2024-03-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockvulnerableapis', '0002_alter_sampledata_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampledata',
            name='node_id',
            field=models.CharField(default='x1', max_length=50),
        ),
        migrations.AlterField(
            model_name='sampledata',
            name='url',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='sampledata',
            constraint=models.UniqueConstraint(fields=('url', 'node_id'), name='unique_url_node_id'),
        ),
    ]
