# Generated by Django 4.2 on 2024-04-16 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockvulnerableapis', '0003_sampledata_node_id_alter_sampledata_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampledata',
            name='url',
            field=models.CharField(max_length=500),
        ),
    ]
